### PR TITLE
Utilities

### PR DESCRIPTION
**Pull request by kubabuda**
- Labels for sheet metal case and phoenix connectors
- script to update HW release and git hash on these labels
- LCSC part numbers where possible, to make ordering from JLCPCB easier

### CODE REVIEW

**Comment by kubabuda** [comment]
This is how the labels turned out:
IMG_3817
IMG_3821

**Comment by kubabuda** [comment]
This is how labels turned out:
IMG_3821
IMG_3817

**Comment by crinq** [comment]
looks like the rows in the pdf are not aligned so you can't cut them in one go

**Comment by kubabuda** [comment]
Good idea, done - have a look if this is what you meant.

**Comment by crinq** [comment]
looks good
LCSC review will take some time

**Comment by kubabuda** [comment]
Just in case, you can start PCBA order on JLCPCB and upload BOM. Their system will show values for parts with valid numbers, and errors where something is wrong ... though probably youre doing it right now

**Comment by kubabuda** [comment]
I fixed some found issues with LCSC part numbers.

**Pull request closed without merging**
