### PR TITLE
Add a sample motor parameter table

### PR DESCRIPTION
**Pull request by c-morley**

### CODE REVIEW

**Comment by c-morley** [comment]
Do you have a reason that this was not acceptable?
Thanks.

**Comment by crinq** [comment]
- there are sample configs in the git
- the pr contains errors and is not a functional config
- there is a parameters section in the doc

**Comment by c-morley** [comment]
Thank you. Where is there a motor parameter sample? The pr is for sample parameters for a particular motor rather then a config. It would  be an example of a proven start point for a motor. I must say it is difficult to get ones head around the docs explanation of some of the parameters - i had hoped it would help the next person. What were the errors please?

**Comment by crinq** [comment]
errors: 
- letter case wrong
- no visible separation between comments and config
- use of units in the config

parameter doc:
- [doc 1](https://github.com/rene-dev/stmbl/blob/master/docs/src/Getting%20Started.adoc#motor-parameters)
- [doc 2](https://github.com/rene-dev/stmbl/blob/master/docs/src/Getting%20Started.adoc#motor)
- [src 1](https://github.com/rene-dev/stmbl/blob/master/src/comps/conf.c)
- [wiki](https://github.com/rene-dev/stmbl/wiki/motor-parameters)

sample config:
- e.g. [fanuc a6-2000](https://github.com/rene-dev/stmbl/blob/master/conf/fanuc_a6-2000.txt)

A better way to improve the docs:
- upload your motor config or a basic exsample, you can use newlines and comments (must be a separate line [example](https://github.com/rene-dev/stmbl/blob/master/conf/bene_sanyo.txt#L49))
- link this config in the docs and explain the config structure and parameters
- keep it simple or separate the important parameters, most parameters are optional and have good default values (like psi)

**Comment by c-morley** [comment]
Thank you for the explanation.
Did you render it ?- it's a table not a config sample.
 The first four links you posted are not sample settings for a particular motor. The fourth does not tell anyone anything about the actual motor. I seem to be failing to get across what I was trying to do - so I will stop trying. But it would be helpful if next time you close a pull request to mention why it was not acceptable.

**Comment by crinq** [comment]
yes i rendered it, but how can a new user go from [this](https://github.com/c-morley/stmbl/blob/bc12e0a50f925dae34c3d4a7516eaf4c22f46f71/docs/src/Getting%20Started.adoc#sample-motor-settings) to [this](https://github.com/rene-dev/stmbl/blob/master/conf/festo.txt)?

the first four links are are documentation for the parameters used in the fifth

**Comment by c-morley** [comment]
Thank you for your patients. I've had some sleep now so i will try again.
When I first started trying to set up a stmbl drive - not being the one who made or understood the details of the drive, nor being a drive expert - the explanation of how to set the parameters leave some questions. If I had a table for instance of known motors with known good starting points, i could have probably extrapolated the information I needed - not to mention if the table happened to actual have the motor I was using I would be golden.
For instance MAX_AC_CUR I was told originally that was continuous current, so you will see I described the motor and mentioned it's continuous current rating and then later you see the cont0.max_ac_current is the same number (You have since corrected me that it is the peak current so I would have fixed that)
I think it is pretty easy to figure out the 'sample parameter table' is just a list of the most critical parameter settings with the most critical motor descriptions. Especially since it's just after the documentation telling you what the parameters are for and how to calculate them. I certainly could add a more through description if you thought it would help.
Once there are half a dozen motors in the table, it would give a good idea about typical settings for different size motors/feedback types.

Since your sample config doesn't mention anything about the actual motor, it's not very helpful without context. If it had said it's a fanuc model xxxx with 3a continuous current, with resolver feedback, with 8 poles (which is what my table told you) then it is helpful.

If you didn't like the table style or where it was placed etc, obviously I could change that.
But as a user of your project, I'm telling you first hand that the information was useful.
More so when I added more motors (unfortunately I burnt out the IRAM chip on the next motor)

**Comment by crinq** [comment]
try this: http://crinq.github.io/js_stuff/stmbl_config/index.html
lot's of errors, tooltips and css missing ...

**Comment by c-morley** [comment]
That is a great idea! If you could add a combo box ,selectable by make/model, that would prefill out the rest of if based on known good data -then we would have a very user friendly utility that would really help people starting out - with less questions to you guys and less 'moving blindly' for users.

**Pull request closed without merging**
